import streamlit as st
import pandas as pd
import numpy as np

# Set page configuration
st.set_page_config(
    page_title="Machine Learning Dashboard",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS to match the UI screenshots
st.markdown("""
<style>
    /* Neon Green & Black Cyber Theme - Layout Fixed */
    
    /* Animations */
    .stApp {
        animation: fadeSlideIn 0.5s ease-out forwards;
    }
    
    @keyframes fadeSlideIn {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
    }
    
    /* Force App & Header to Black */
    [data-testid="stAppViewContainer"], .stApp {
        background-color: #050505 !important;
    }
    
    header[data-testid="stHeader"] {
        background: transparent !important;
    }
    
    /* Sidebar Styling */
    [data-testid="stSidebar"] {
        background-color: #0a0a0a !important;
        border-right: 1px solid #1a1a1a !important;
    }
    
    /* Typography Overrides */
    h1, h2, h3, h4, h5, h6, p, span, label {
        color: #e0e0e0 !important;
    }
    
    /* Input & Selectbox Dropdown Fixes */
    [data-testid="stSelectbox"] > div > div > div {
        background-color: #050505 !important;
        border: 1px solid #39ff14 !important;
        color: #39ff14 !important;
    }
    
    div[data-baseweb="popover"] ul, div[data-baseweb="select"] {
        background-color: #050505 !important;
        border: 1px solid #39ff14 !important;
    }
    
    li[role="option"] {
        color: #39ff14 !important;
        background-color: #050505 !important;
    }
    
    li[role="option"]:hover, li[role="option"][aria-selected="true"] {
        background-color: rgba(57, 255, 20, 0.3) !important;
        color: #ffffff !important;
    }
    
    /* Number Inputs */
    [data-testid="stNumberInput"] > div > div > input {
        background-color: #050505 !important;
        color: #39ff14 !important;
        border: 1px solid #39ff14 !important;
    }
    
    .main-title {
        color: #39ff14 !important; /* Neon Green */
        font-size: 32px !important;
        font-weight: 800 !important;
        letter-spacing: 1px !important;
        margin-bottom: 2px !important;
        font-family: 'Courier New', Courier, monospace !important;
        text-shadow: 0 0 10px rgba(57, 255, 20, 0.4) !important;
        text-transform: uppercase;
    }
    
    .sub-title {
        color: #666666 !important;
        font-size: 13px !important;
        margin-bottom: 30px !important;
        font-weight: 600 !important;
        text-transform: uppercase !important;
        letter-spacing: 2px !important;
    }
    
    /* Hide the empty boxes generated by user's empty markdown divs */
    div.css-1r6slb0, div.css-12oz5g7 {
        display: none !important; 
    }
    
    /* Add panels to the actual layout columns instead */
    [data-testid="column"] {
        background-color: #0a0a0a !important;
        border: 1px solid #1f1f1f !important;
        border-radius: 4px !important;
        padding: 20px !important;
        transition: all 0.2s ease !important;
    }
    
    [data-testid="column"]:hover {
        border-color: rgba(57, 255, 20, 0.4) !important;
        box-shadow: 0 0 15px rgba(57, 255, 20, 0.05) !important;
    }
    
    /* Buttons - Neon Hacker Style */
    .stButton>button {
        background-color: #050505 !important;
        color: #39ff14 !important;
        border: 1px solid #39ff14 !important;
        border-radius: 2px !important;
        font-weight: 600 !important;
        letter-spacing: 1px !important;
        text-transform: uppercase !important;
        transition: all 0.2s ease !important;
        font-family: 'Courier New', Courier, monospace !important;
        box-shadow: 0 0 5px rgba(57, 255, 20, 0.2) !important;
    }
    
    .stButton>button:hover {
        background-color: rgba(57, 255, 20, 0.1) !important;
        box-shadow: 0 0 15px rgba(57, 255, 20, 0.6) !important;
        transform: translateY(-2px) !important;
    }
    
    .stButton>button:active {
        transform: translateY(0) !important;
        box-shadow: 0 0 5px rgba(57, 255, 20, 0.4) !important;
    }
    
    /* File Uploader Aggressive Fix */
    [data-testid="stFileUploader"],
    [data-testid="stFileUploader"] > div,
    [data-testid="stFileUploader"] section,
    [data-testid="stFileUploadDropzone"] {
        background-color: #050505 !important;
    }
    
    [data-testid="stFileUploadDropzone"] {
        border: 1px dashed #39ff14 !important;
        border-radius: 4px !important;
        padding: 16px !important;
    }
    
    [data-testid="stFileUploadDropzone"] * {
        color: #39ff14 !important;
        background-color: #050505 !important;
    }
    
    [data-testid="stFileUploadDropzone"] button {
        background-color: #0a0a0a !important;
        border: 1px solid #39ff14 !important;
        color: #39ff14 !important;
        border-radius: 4px !important;
        padding: 4px 12px !important;
    }
    
    [data-testid="stFileUploadDropzone"]:hover {
        background-color: #0a0a0a !important;
        box-shadow: 0 0 15px rgba(57, 255, 20, 0.3) !important;
    }

    /* Slider Fix (Make it neon green instead of blue) */
    .stSlider > div > div > div > div {
        background-color: #39ff14 !important; 
    }
    .stSlider > div > div > div > div[role="slider"] {
        background-color: #050505 !important;
        border: 2px solid #39ff14 !important;
        box-shadow: 0 0 5px #39ff14 !important;
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state variables
if 'page' not in st.session_state:
    st.session_state.page = 'Dashboard'
if 'dataset' not in st.session_state:
    st.session_state.dataset = None
if 'preprocessed_data' not in st.session_state:
    st.session_state.preprocessed_data = None
if 'trained_models' not in st.session_state:
    st.session_state.trained_models = {}
if 'active_model_name' not in st.session_state:
    st.session_state.active_model_name = None

# Sidebar Navigation
with st.sidebar:
    st.markdown('<div class="main-title">MACHINE LEARNING DASHBOARD</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-title">v2.0 - Streamlit</div>', unsafe_allow_html=True)
    
    st.write("") # Spacer
    
    # Navigation items using buttons styled to look like links
    pages = {
        'Dashboard': '🏠',
        'Data Explorer': '📊',
        'Model Training': '⚙️',
        'Visualizations': '📈',
        'Predictions': '🎯',
        'Model History': '📋',
        'Settings': '🔧'
    }
    
    for page_name, icon in pages.items():
        # Handle state changes
        if st.sidebar.button(f"{icon} {page_name}", use_container_width=True, 
                             type="primary" if st.session_state.page == page_name else "secondary"):
            st.session_state.page = page_name
            st.rerun()

    st.write("") # Spacer
    st.write("") # Spacer
    
    # Bottom info section
    if st.session_state.dataset is not None:
        st.markdown(f"**Current Dataset:** {st.session_state.dataset_name}")
        rows, cols = st.session_state.dataset.shape
        # Assuming 'Label' is the target class
        classes = st.session_state.dataset['Label'].nunique() if 'Label' in st.session_state.dataset.columns else "Unknown"
        st.caption(f"Rows: {rows} | Features: {cols-1} | Classes: {classes}")
    
    if st.sidebar.button("NEW SESSION", use_container_width=True):
        for key in list(st.session_state.keys()):
            del st.session_state[key]
        st.rerun()

# Router
if st.session_state.page == 'Dashboard':
    import pages_ui.dashboard as ui
    ui.render()
elif st.session_state.page == 'Data Explorer':
    import pages_ui.data_explorer as ui
    ui.render()
elif st.session_state.page == 'Model Training':
    import pages_ui.model_training as ui
    ui.render()
elif st.session_state.page == 'Visualizations':
    import pages_ui.visualizations as ui
    ui.render()
elif st.session_state.page == 'Predictions':
    import pages_ui.predictions as ui
    ui.render()
else:
    st.title(st.session_state.page)
    st.info(f"{st.session_state.page} functionality is under development.")
